### ISSUE TITLE
Feature: Enabling better extensibility & framework tooling integration

### ISSUE THREAD

**Issue by addyosmani** [webpack/webpack-cli#101]
_Working with @ev1stensberg @TheLarkInn & @developit on this one_

Webpack CLI aims to offer users the ability to scaffold a fine-grained Webpack configuration with flexible support for custom templates. This will enable a number of powerful workflows, including the ability for other framework tooling to build on top of it to create SPAs and [PWAs](https://developers.google.com/web/progressive-web-apps/) in a low-friction way. 

This issue looks at ways in which we can continue to enable some of that work using Yeoman in tandem with the on-going [V1 label](https://github.com/webpack/webpack-cli/labels/v1).

### Leveraging Yeoman’s generator system 

On reviewing the work done on the [Polymer CLI](https://github.com/Polymer/polymer-cli/search?p=1&q=generator&type=&utf8=%E2%9C%93) to enable the same user-installable custom template workflow, Webpack discovered several wins possible by [switching over the CLI](https://github.com/webpack/webpack-cli/pull/93) to using the Yeoman generator system under the hood.

Early prototypes of the Webpack CLI in fact shared similar functionality. It had a `parser` module which was circular that provided a scaffold through Inquirer the same way Yeoman would. 

It was later discovered the behavior Even and the team really wanted was provided through the Yeoman helpers on top of Inquirer. This would provide flexibility in terms of extending the scaffolding - e.g composition support for tying together a scaffold with other Yeoman-based tools like a generator adding support for Babel to a project or even Preact. 

This sets up the CLI for helping with a number of modern developer workflows. It could scaffold an optimized Webpack config with support for Progressive Web Apps. As the CLI deals with scaffolding through an AST, reading from an object inside the Yeoman generator can provide an entry point for code-splitting, Service Worker caching, favicon wiring, long-term caching and a number of other performance related features Webpack can offer. 

### Alpha/Beta for V1

The early versions of Webpack CLI may have templates that are a little more verbose, but will get slimmer as time goes on. In the future, Even and the team will be aiming to make it possible to integrate Webpack features on the fly (via AST transformations) to existing configurations. 

There may also be the possibility of a `webpack init` scaffolding an extension of a Yeoman generator with some additional Webpack utility functions. This enables authors to not have to directly use the Webpack CLI to get a scaffold functional. It also means being able to support scaffolding outside CLI environments.

### CLI 🤖 

- [x] (Yeoman) [PR for getArgument()](https://github.com/yeoman/generator/pull/1011). Enable making it easier to expose prompt answers to env.
- [x] [AST transformations](https://github.com/webpack/webpack-cli/issues/29) for the init feature 
- [x] Move ASTs internally to webpack-addons and internal ASTs to Yeoman methods
- [x] (Yeoman) Hook up functionality to the internal control flow
- [x] [Refactor logic in lib/creator](https://github.com/webpack/webpack-cli/issues/98) post Yeoman switch
- [x] (Yeoman) Use composeWith in order to mount other generators when you do: `webpack-cli --init webpack-addons-ylvis webpack-addons-thefox`
- [x] Well reasoned add-ons story, carrying on from [#42](https://github.com/webpack/webpack-cli/issues/42)
- [x] Minor issues on windows and prettier support, #111

### Scaffolds 🏗 

- [x] Most basic Webpack CLI scaffold that works post Yeoman switch
- [x] Webpack CLI scaffold for PWA: vendor + app code-splitting, long-term caching, SW caching. Heavily inspired by existing examples. Could also factor in [#95](https://github.com/webpack/webpack-cli/issues/95).

### Ecosystem 📦 

- [ ] Coordinate with Jason Miller on [Preact CLI](https://github.com/developit/preact/issues/496) usage of Webpack CLI under the hood
- [x] An ecosystem for the init feature (by extending the Yeoman generator) - i.e ability to use Yeoman generators in other tools, improving the available helpers in both Webpack CLI and there that leverage max power for users in terms of AST part.

### Docs 📚 
- [x] Webpack CLI getting started
- [x] Webpack CLI API surface (post generator work)
- [x] Webpack CLI PWA template

**Comment by addyosmani** [comment]
> Webpack CLI scaffold for PWA

To give the thread a quick update on where we are here. We've prototyped an add-on using the output of https://github.com/vuejs/pwa as a POC. I need to put together or figure out what the ideal Webpack output for this step would be. We've got a few options:

* Just the module bundling/serving parts that a PWA would need (we could say code-splitting, precaching, preloading (maybe), long-term caching). Stay very specific to what Webpack can do well here.

* Go for a more complete template that includes a framework. My hesitation here is that you start to compete with framework CLIs rather than telling the story of how they can build on top of Webpack CLI's scaffolding + AST handling for build pipeline stuff. 

Leaning towards the first of these options. You could imagine the output not being too dissimilar to https://github.com/GoogleChrome/preload-webpack-plugin/blob/master/demo/webpack.config.js

**Comment by ev1stensberg** [comment]
I'm closing this now 🎉 by CC-ing @developit . Feel free to reach out to us if you want to customize preact cli to eject configurations or to add additional functionality to preact-cli!
