### ISSUE TITLE
integrate init command with CLI by default

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#1509]
**Is your feature request related to a problem? Please describe.**
As part of roadmap, we like to integrate `init` by default.
This is the tracker issue and discussion thread for this work.

**Describe the solution you'd like**

- [x] Robust tests for `init`'s current features - completed - #1508, #1419 
- [x] Refactor `init` and add/remove features from it - completed - #1590 
       - Add flag to force configuration generation.
- [x] Add tests for the previous step changes (if any) - completed - #1590 
- [x] Integrate it with CLI - completed - #1609 
- [x] Add integration tests for verifying integration,  - completed - #1609

**Describe alternatives you've considered**
N/A

**Additional context**
Roadmap #717 

/cc @evilebottnawi

**Comment by evilebottnawi** [comment]
Yes, good job :+1:

One strange thing - `init` command doesn't generate config by default, I think main purpose init is to generate config + additional commands to improve it

**Comment by rishabh3112** [comment]
It is 0CJS by default. Anytime a situation can be handled by defaults, configuration is not generated.

It gets generated when we need something like CSS preprocessors, etc.

Would add a test for that in the PR I have sent for init tests. #1508

**Comment by evilebottnawi** [comment]
@rishabh3112 Agree, but sometimes you really need integrate configuration, so will be great have cmmand/flag for this

**Comment by rishabh3112** [comment]
Okay, lets do it in the second step in above list.

**Comment by rishabh3112** [comment]
Completed, closing the issue now 😀
