### ISSUE TITLE
feature: new init generator

### ISSUE THREAD

**Issue by rishabh3112** [webpack/webpack-cli#2430]
**Is your feature request related to a problem? Please describe.**
Currently, the init generation is a bad DX with support for custom scaffolds completely broken.

**Describe the solution you'd like**
Generate pre-defined configurations instead of creating one using AST transforms. The implementation will be done in steps:

- [x] Simplify the generation flow for init (#2429)
- [x] Add default template for init (#2429)
- [x] Add tests for init
- [x] Update documentation

**Describe alternatives you've considered**
N/A

**Additional context**
#2409
/cc @webpack/cli-team

**Comment by alexander-akait** [comment]
After this we should not have `jscodeshift` in our deps

**Comment by alexander-akait** [comment]
Also we should always generate `webpack.config.js`

**Comment by alexander-akait** [comment]
And we should not exist with `-1` code when somebody press `CRTL + C`  on init (try it using `npm init`)

**Comment by alexander-akait** [comment]
@rishabh3112 What is status? I want to finish it for the next release

**Comment by rishabh3112** [comment]
> @rishabh3112 What is status? I want to finish it for the next release

 It works as we need. I have added tests as well. Will rebase and then we can merge it.

**Comment by alexander-akait** [comment]
@rishabh3112 Do we drop `jscodeshift` from our deps?

**Comment by rishabh3112** [comment]
> @rishabh3112 Do we drop `jscodeshift` from our deps?

Yup its not needed now for init. Will remove it from deps as well.

**Comment by rishabh3112** [comment]
# Status
1. Simplification of code structure done
2. Created default template
2. Testing is done as well

# Nice to dos 
1. Add questioning for webpack configuration. (Trying on #2429 it self)

**Comment by rishabh3112** [comment]
All done ✨ 
Will be adding more templates for `react`, `vue`, `node-packages` etc in further PRs 😎

**Comment by rishabh3112** [comment]
Documentation will be tracked on https://github.com/webpack/webpack.js.org/issues/4741

**Comment by rishabh3112** [comment]
Now available in latest release ✅ 

TODO: Adding templates for common usecases (https://github.com/webpack/webpack-cli/issues/2430#issuecomment-793683956) - WIP

**Comment by rishabh3112** [comment]
### Todo
- [ ] Add support add varied options as per `mode` (eg. `css-minimizer-webpack-plugin` only in production)
- [ ] Update Mini-CSS-extract-plugin configuration after above change. For example:
  ```
  Do you want to extract CSS for every file?
  - Yes
  - Only for production
  - No
  ```

**Comment by evenstensberg** [comment]
PWA support too?

**Comment by alexander-akait** [comment]
Do you need plugin for service workers?

**Comment by evenstensberg** [comment]
https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin

**Comment by jamesgeorge007** [comment]
> PWA support too?

WIP

**Comment by rishabh3112** [comment]
New init architecture has been shipped. We will track development of more templates in #2832.
